ACTIVE_STATUSES = {"PENDING", "RUNNING"}
TERMINAL_STATUSES = {"SUCCEEDED", "FAILED", "CANCELED"}

JOB_TYPE_DEEP_ANALYSIS = "DEEP_ANALYSIS"
JOB_TYPE_OCR_EXTRACTION = "OCR_EXTRACTION"
PROVIDER_CODEX_CLI = "codex_cli"
PROVIDER_LOCAL_OCR = "local_ocr"
PROVIDER_MODE_EXEC = "exec"
PROVIDER_MODE_MOCK = "mock"
PROVIDER_MODE_TESSERACT = "tesseract"
PROVIDER_MODE_APP_SERVER = "app_server"
PROVIDER_MODE_APP_SERVER_FALLBACK_EXEC = "app_server_fallback_exec"

ERROR_NO_SOURCE_TEXT = "NO_SOURCE_TEXT"
ERROR_CLI_NOT_AUTHENTICATED = "CLI_NOT_AUTHENTICATED"
ERROR_CLI_TIMEOUT = "CLI_TIMEOUT"
ERROR_CLI_OUTPUT_INVALID = "CLI_OUTPUT_INVALID"
ERROR_FILE_NOT_FOUND = "FILE_NOT_FOUND"
ERROR_UNKNOWN = "UNKNOWN_ERROR"
ERROR_APP_SERVER_UNAVAILABLE = "APP_SERVER_UNAVAILABLE"
ERROR_APP_SERVER_PROTOCOL = "APP_SERVER_PROTOCOL_ERROR"
ERROR_APP_SERVER_TIMEOUT = "APP_SERVER_TIMEOUT"
ERROR_CANCEL_FAILED = "CANCEL_FAILED"
